### ISSUE TITLE
--tmpfs with mode=777

### ISSUE THREAD

**Issue by robsmith11** [containers/bubblewrap#131]
Is it necessary to have --tmpfs use mode=755?  I'm running sshd in bwrap and would like to allow other users to log in and be able to write to /tmp.

**Comment by cgwalters** [comment]
Yeah...we should support this.  I think things get a little interesting though since we'd end up needing to do something systemd-tmpfiles.d like (support user/groups).

You should be able to work around this by creating the directory inside the container - inject code to do whatever mkdirs etc you want as whatever uids, then exec your app.

**Comment by smcv** [comment]
#406 implements options that would let you use `--perms 1777 --tmpfs /tmp`.

The default continues to be 0755 to avoid behaviour changes.
