### ISSUE TITLE
Examples don't work with Debian 9 and Ubuntu 17.04

### ISSUE THREAD

**Issue by glasen** [containers/bubblewrap#200]
Hi,

i'm currently testing bubblewrap on our server and i have the problem that bubblewrap can't "execp" any commands:
```
glasen@wizzard:~/Downloads$ ./bubblewrap-shell.sh 
execvp /bin/sh: No such file or directory

```
It only works when using "--ro-bind  / /" which is a bit of contra-productive. When i start the script under ArchLinux it works perfectly.

**Comment by tmiasko** [comment]
On Debian I had to ro-bind /bin, /sbin, /lib and /lib64 directories instead of symlinking those from usr. The complete bubblewrap-shell.sh script with changes looks as follows:

```sh
#!/usr/bin/env bash
set -euo pipefail
(exec bwrap \
      --ro-bind /usr /usr \
      --ro-bind /lib /lib \
      --ro-bind /lib64 /lib64 \
      --ro-bind /bin /bin \
      --ro-bind /sbin /sbin \
      --dir /tmp \
      --dir /var \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --ro-bind /etc/resolv.conf /etc/resolv.conf \
      --chdir / \
      --unshare-all \
      --share-net \
      --die-with-parent \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --setenv PS1 "bwrap-demo$ " \
      --file 11 /etc/passwd \
      --file 12 /etc/group \
      /bin/sh) \
    11< <(getent passwd $UID 65534) \
    12< <(getent group $(id -g) 65534)
```

**Comment by cgwalters** [comment]
Yeah, we need to tweak the demo shell to detect the distro bits like `/usr/lib64` vs Debian multiarch.

**Comment by valoq** [comment]
Here are some additional example scripts that include modified versions for debian stretch
https://github.com/valoq/bwscripts

**Comment by smcv** [comment]
> the distro bits like `/usr/lib64` vs Debian multiarch

Debian multiarch isn't the problem here - multiarch libraries are in subdirectories of `lib`, and the x86_64 runtime linker is still `/lib64/ld-linux-x86-64.so.2` (actually a symlink into `lib/x86_64-linux-gnu`) as specified by the cross-distro psABI, so as long as `/lib*` are all made available it will work fine.

The issue here is that Debian doesn't usually have [merged `/usr`](https://wiki.debian.org/UsrMerge), unlike e.g. Fedora. Since stretch it's supported as an option, but it isn't done during installation or upgrade by default.
