### ISSUE TITLE
Bubblewrap doesn't work with Vulkan since 0.3.3-2

### ISSUE THREAD

**Issue by trialism** [containers/bubblewrap#328]
Vulkaninfo error:

```
Surface type : VK_KHR_xlib_surface
/home/trialism/Workspace/Vulkan-Tools/vulkaninfo/vulkaninfo.c:1587: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by trialism** [comment]
Tested with:

```
bwrap --dev-bind / / bash
```

**Comment by smcv** [comment]
`bwrap --dev-bind / / vulkaninfo` is working fine for me, with Intel hardware and Debian's bwrap 0.3.3-2.

What OS distribution and version are you using, and what GPU/driver?

You say this is a problem since 0.3.2, which suggests that an older version of bwrap worked. Which older version? Did 0.3.1 work?

Please could you try running vulkaninfo under `strace` to try to find out more specifically which syscall(s) worked with the older version but not 0.3.2?

**Comment by trialism** [comment]
A correction: 0.3.3-1(1st pkg [here](https://archive.archlinux.org/packages/b/bubblewrap/)) is the latest working version, not 0.3.2-x.
I'm using an rtx 2080 with manjaro. I tried drivers from version 418 to 435.21.
Applications can't access vulkan at all from a bubblewrap sandbox. vulkaninfo fails [here](https://github.com/KhronosGroup/Vulkan-Tools/blob/master/vulkaninfo/vulkaninfo.c#L1587)(at the very beginning).

**Comment by smcv** [comment]
What changed in Arch Linux between 0.3.3-1 and 0.3.3-2? The upstream bubblewrap project is not responsible for particular distributions' packaging choices.

Is this table correct?

```
                                           0.3.3-1    0.3.3-2
RTX 2080, proprietary NVIDIA driver         works      fails
Intel GPU, Mesa driver                      works      works
```

Please could you try running vulkaninfo under strace to try to find out more specifically which syscall(s) worked with the older version but not the newer version? I can't do anything with "vulkaninfo exits unsuccessfully" - there must be something failing before that, that causes it to decide to exit unsuccessfully.

**Comment by smcv** [comment]
> What changed in Arch Linux between 0.3.3-1 and 0.3.3-2?

It looks as though the answer is: bwrap is no longer setuid root by default, because newer Arch kernels don't usually need that unless you are using `linux-hardened`.

Please try replacing `bubblewrap` with `bubblewrap-suid` on your NVIDIA system? If `bubblewrap` fails but `bubblewrap-suid` works, then that would narrow down what the problem might be.

**Comment by trialism** [comment]
@smcv thanks, bubblewrap-suid works! I will contact the package's maintainer.

**Comment by Sporif** [comment]
The problem is the Nvidia driver does not work properly with user namespaces with bubblewrap. If unprivileged user namespaces are enabled then bwrap without setuid (`bubblewrap >= 0.3.3-2`) will create a user namespace by default. But setuid bwrap (`bubblewrap <=0.3.3-1` or `bubblewrap-suid`) will not create user namespaces by default so the problem never surfaced if you didn't use `--unshare-user`.

So you can try `bwrap --dev-bind / / --unshare-user vulkaninfo` and even with `bubblewrap-suid` it will output `failed with VK_ERROR_INITIALIZATION_FAILED`.

In fact Xorg will crash if you use `vkcube` instead of `vulkaninfo` and `glxgears` will show a black screen when it goes fullscreen while the compositor was disabled or unredirected. 

Since this isn't a problem with Mesa then it must be an Nvidia driver quirk. Which is not surprising since it had [problems with network namespaces](https://devtalk.nvidia.com/default/topic/1045121/processes-inside-network-namespaces-can-t-use-flipping-and-g-sync/) recently fixed.

But it is possible to workaround this issue because LXD (which uses user namespaces by default) has a gpu option that doesn't cause the above issues. I think this user namespace issue is something to do with the ownership of `/dev/nvidia*` and `/dev/dri`. Because with LXD the ownership of `/dev/nvidia*` and `/dev/dri` are `root:root` (while most  other /dev files are `nobody:nobody`). But with bubblewrap all files other than the user's are `nobody:nobody`.

**Comment by alexlarsson** [comment]
Flatpak uses bubblewrap, and on my (F30) machine it is not setuid, yet the nvidia drivers work fine. 

And I can do:
```
$ flatpak run --command=./vulkaninfo --device=dri -d org.gnome.eog  | head
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.114



Instance Extensions:
====================
Instance Extensions     count = 18
        VK_EXT_acquire_xlib_display         : extension revision  1
        VK_EXT_debug_report                 : extension revision  9
        VK_EXT_debug_utils                  : extension revision  1
        VK_EXT_direct_mode_display          : extension revision  1
...
```

**Comment by Sporif** [comment]
Interesting, I haven't tried flatpak yet. Are unprivileged user namespaces enabled on your machine?

**Comment by alexlarsson** [comment]
Or:
```
$ bwrap --dev-bind / / --unshare-user vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.114

...
```

**Comment by alexlarsson** [comment]
And yes, this is with user namespaces.

**Comment by Sporif** [comment]
Then it's very weird it doesn't work for me. 

 - What OS and Nvidia driver are you using
 - Is Xorg running rootless?
 - Is modeset=Y on `nvidia_drm` (`sudo systool -vm nvidia_drm | grep modeset`)

**Comment by alexlarsson** [comment]
This is a standard fedora 30 install with:
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  440.44  Sun Dec  8 03:38:56 UTC 2019
GCC version:  gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC) 
$ sudo systool -vm nvidia_drm | grep modeset
    modeset             = "Y"
```
Xorg is xorg-x11-server-Xorg-1.20.5-7.fc30.x86_64 and runs as my user.

**Comment by alexlarsson** [comment]
Can you try:
```
$ bwrap --dev-bind / / --unshare-user strace -y -o log  vulkaninfo 
```
And look at the end of `log` and see what seems to fail?

**Comment by Sporif** [comment]
Well I can't tell what's the cause so here are the logs of with and without bwrap.
[log_normal.txt](https://github.com/containers/bubblewrap/files/4004928/log_normal.txt)
[log_userns.txt](https://github.com/containers/bubblewrap/files/4004929/log_userns.txt)

**Comment by alexlarsson** [comment]
So, the main differences seem to start on line 9046 in log_userns.txt and 8764 in log_normal.txt, where after looking at /proc/modules and /proc/driver/nvidia/params it stats /dev/nvidiactl:

userns:
```
stat("/dev/nvidiactl", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xc3, 0xff), ...}) = 0
chmod("/dev/nvidiactl", 0666)           = -1 EPERM (Operation not permitted)
stat("/usr/bin/nvidia-modprobe", {st_mode=S_IFREG|S_ISUID|0755, st_size=33928, ...}) = 0
geteuid()                               = 1000
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f9165e7e490) = 507426
wait4(507426, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 507426
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=507426, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
```

normal:
```
stat("/dev/nvidia-modeset", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xc3, 0xfe), ...}) = 0
openat(AT_FDCWD, "/dev/nvidia-modeset", O_RDWR|O_CLOEXEC) = 5</dev/nvidia-modeset>
fcntl(5</dev/nvidia-modeset>, F_GETFD)  = 0x1 (flags FD_CLOEXEC)
ioctl(4</dev/nvidiactl>, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffcea567c40) = 0
ioctl(4</dev/nvidiactl>, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7ffcea567c40) = 0
```

Clearly there is something about the permissions that are different in the user namespace, probably beacuse other uid/gids are not mapped in the user ns.

**Comment by alexlarsson** [comment]
However when I run the same in bwrap it does:
```
stat("/dev/nvidiactl", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xc3, 0xff), ...}) = 0
chmod("/dev/nvidiactl", 0666)           = -1 EPERM (Operation not permitted)
stat("/usr/bin/nvidia-modprobe", 0x7ffca8c82fb0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/driver/nvidia/params", O_RDONLY) = 4</proc/driver/nvidia/params>
```
Which is the same as yours, yet it works, so maybe that is not the main cause.

**Comment by alexlarsson** [comment]
Actually comparing it at the end it seems like it connects to the xserver, authenticates and then does some request that fails:

At line 9306 in log_user:
```
writev(13<socket:[4390734]>, [{iov_base="l\0\v\0\0\0\22\0\20\0\0\0", iov_len=12}, {iov_base="", iov_len=0}, {iov_base="MIT-MAGIC-COOKIE-1", iov_len=18}, {iov_base="\0\0", iov_len=2}, {iov_base="i\361\331\376\214Mf\212u\246\22\3752\336U\7", iov_len=16}, {iov_base="", iov_len=0}], 6) = 48
recvfrom(13<socket:[4390734]>, "\1\0\v\0\0\0K\3", 8, 0, NULL, NULL) = 8
recvfrom(13<socket:[4390734]>, "\271\235\270\0\0\0\240\3\377\377\37\0\0\1\0\0\24\0\377\377\1\7\0\0  \10\377\0\0\0\0"..., 3372, 0, NULL, NULL) = 3372
poll([{fd=13<socket:[4390734]>, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=13, revents=POLLOUT}])
writev(13<socket:[4390734]>, [{iov_base="\1\0\10\0\0\0\240\3\322\1\0\0\0\0\0\0\0\1\0\1\0\0\1\0!\0\0\0\0\0\0\0"..., iov_len=52}], 1) = 52
poll([{fd=13<socket:[4390734]>, events=POLLIN}], 1, -1) = 1 ([{fd=13, revents=POLLIN}])
recvmsg(13<socket:[4390734]>, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\2\0\0\0\0\0\\\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
write(2</dev/pts/6>, "/build/vulkan-tools/src/Vulkan-T"..., 68) = 68
```
That is authenticating to X with the magic cookie, getting an "OK" and then some x request, a reply and then it writes the failure to stdout. 

Whereas in the normal case the reply must be ok, because it follows up by dlopening libxcb-glx.so:
```
writev(14<socket:[4393492]>, [{iov_base="l\0\v\0\0\0\22\0\20\0\0\0", iov_len=12}, {iov_base="", iov_len=0}, {iov_base="MIT-MAGIC-COOKIE-1", iov_len=18}, {iov_base="\0\0", iov_len=2}, {iov_base="i\361\331\376\214Mf\212u\246\22\3752\336U\7", iov_len=16}, {iov_base="", iov_len=0}], 6) = 48
recvfrom(14<socket:[4393492]>, "\1\0\v\0\0\0K\3", 8, 0, NULL, NULL) = 8
recvfrom(14<socket:[4393492]>, "\271\235\270\0\0\0\240\3\377\377\37\0\0\1\0\0\24\0\377\377\1\7\0\0  \10\377\0\0\0\0"..., 3372, 0, NULL, NULL) = 3372
poll([{fd=14<socket:[4393492]>, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=14, revents=POLLOUT}])
writev(14<socket:[4393492]>, [{iov_base="\1\0\10\0\0\0\240\3\322\1\0\0\0\0\0\0\0\1\0\1\0\0\1\0!\0\0\0\0\0\0\0"..., iov_len=52}], 1) = 52
poll([{fd=14<socket:[4393492]>, events=POLLIN}], 1, -1) = 1 ([{fd=14, revents=POLLIN}])
recvmsg(14<socket:[4393492]>, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\2\0\0\0\0\0\\\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 15</etc/ld.so.cache>
fstat(15</etc/ld.so.cache>, {st_mode=S_IFREG|0644, st_size=296801, ...}) = 0
mmap(NULL, 296801, PROT_READ, MAP_PRIVATE, 15</etc/ld.so.cache>, 0) = 0x7fd37b726000
close(15</etc/ld.so.cache>)             = 0
openat(AT_FDCWD, "/usr/lib/libxcb-glx.so.0", O_RDONLY|O_CLOEXEC) = 15</usr/lib/libxcb-glx.so.0.0.0>
```

**Comment by alexlarsson** [comment]
Maybe you can get some kind of log from the xserver side?

**Comment by Sporif** [comment]
I know it's definitely to do with X since the command works when Xorg isn't running. Problem is there is no relevant output in the Xorg (`.local/share/xorg/Xorg.0.log`) or session log. I tried with `-verbose 6 logverbose 6`.

**Comment by Sporif** [comment]
This makes no sense to me now. I just tried flatpak and it works.

**Comment by Sporif** [comment]
Maybe the cause is that flatpak shows `/proc/self/uid_map="1000          0          1"` but with `bwrap --dev-bind / / --unshare-user` it's `/proc/self/uid_map="1000       1000          1" ?`

**Comment by Sporif** [comment]
At last I found the cause! And of course it was something trivial. The [nvidia-utils](https://www.archlinux.org/packages/extra/x86_64/nvidia-utils/) package in Arch Linux's  contains the file `/usr/bin/nvidia-modprobe` and it is setuid. Not passing it through or adding `--ro-bind /usr/bin/true /usr/bin/nvidia-modprobe` is enough to fix it.

I assume it's because inside a bwrap user namespace root is unmapped so nvidia-modprobe calls to create devices (probably the modeset device) fail and the nvidia driver errors out as a result. Not a problem with LXC/D since root is mapped and in Fedora & Flatpak containers `/usr/bin/nvidia-modprobe` doesn't exist.

And I guess it only happened inside Xorg because the Nvidia driver only calls nvidia-modprobe then?
