### ISSUE TITLE
Feature request: hide original filesystem

### ISSUE THREAD

**Issue by xi** [containers/bubblewrap#365]
My goal was to sandbox a shared tmux session for pair programing. As part of that, I wanted to hide `/home` and only share the relevant project folder.

I am using bubblewrap 0.2.1 on ubuntu bionic.

### Allow list

My first attempt was to only bind those directories I really needed. However, it didn't work:

```
$ bwrap --ro-bind /bin /bin --bind $PWD $PWD /bin/bash
bwrap: execvp /bin/bash: No such file or directory
```

### tmpfs

My second attempt was inspired by  examples I found in the [arch wiki](https://wiki.archlinux.org/index.php/Bwrap#MuPDF):

```
$ bwrap --ro-bind / / --dev /dev --proc /proc --tmpfs /tmp --tmpfs /home --bind $PWD $PWD /bin/bash
```

This *did* work but turned out to be a footgun: At some point I moved some files to `$HOME`. After closing bwrap these files were gone. You could say this was my fault for using it wrong but I think using a writeable tmpfs for this just invites trouble.

### ro-bind empty dir

So the next attempt was to use a readonly bind but that didn't work either:

```
$ mkdir /tmp/empty
$ bwrap --ro-bind / / --ro-bind /tmp/empty /home --bind $PWD $PWD /bin/bash
bwrap: Can't mkdir parents for /home/user/somepath: Read-only file system
```

---

I am not sure: Maybe there already is a good solution for this. In that case it might be helpful to add an example to the documentation. Or there is not solution, in which case this is a feature request.

**Comment by smcv** [comment]
Try this:

```
$ bwrap \
--ro-bind / / \
--dev /dev \
--proc /proc \
--tmpfs /tmp \
--tmpfs /home \
--bind $PWD $PWD \
--remount-ro /home \
/bin/bash
```

The difference between this and your second attempt is that after doing all the setup that needs to create mount points in `/home`, it remounts `/home` read-only.

The result (in this example `/home/smcv/src` is my equivalent of your `$PWD`):

```
smcv@espresso:~$ touch /home/smcv/nope
touch: cannot touch '/home/smcv/nope': Read-only file system
smcv@espresso:~$ touch /home/smcv/src/this-works
```

**Comment by smcv** [comment]
Note that bwrap is primarily intended to be used by the developers of higher-level sandboxing arrangements like Flatpak to build their intended security model, rather than used directly: it gives you a toolbox, but it makes no attempt to ensure that you are using the tools correctly. I don't know what your security model is, and I have not attempted to audit whether the rest of your sample command-line is suitable for it.

If you don't trust the pair programmer, giving them access to your D-Bus session bus (and the rest of `$XDG_RUNTIME_DIR`) and the ability to enumerate and ptrace processes outside the container (by not using `--unshare-pid`) are among many examples of things they could misuse.

**Comment by xi** [comment]
Thanks for the quick feedback. So I guess this is both possible (with `--remount-ro`) and out-of-scope. I still hope this was useful feedback.
