### ISSUE TITLE
--unshare-pid should share containers pid with host

### ISSUE THREAD

**Issue by damianatorrpm** [containers/bubblewrap#373]
I guess this is the correct place for https://github.com/flatpak/flatpak/issues/3600
Patching flatpak to remove --unshare-pid works fine.

Tools that get the pid from the window/surface/xwayland surface
always report either 0 or 2 as PID (affected X11, wayland (xwayland flatpak))
wayland native work fine

```
wmctrl -lp 
swaymsg -t get_tree | grep pid
```

**Comment by alexlarsson** [comment]
The entire point of the  --unshare-pid option is to make a separate set of pids. Why would you want this to not do anything?

**Comment by damianatorrpm** [comment]
@alexlarsson I need to be able to query the PID using the window. This is also part of the wayland protocol. The wl_client has pid. This PID should refer to the PID in the namespace of the compositor,
yet the PID you get is the one from inside the namespace.

Yet, for processes that are spawned with X as backend and not wayland it seems that the process has to know it's outer PID to set _NET_WM_PID

**Comment by alexlarsson** [comment]
Wayland is fine here, it uses wl_client_get_credentials() which gets the pid using  SO_PEERCRED which will return the pid in the calling users pid namespace, so the compositor will see the "globally unique" pid.

But, for _NET_WM_PID it is harder. This is ancient APIs that are all set manually by each client, and interpreted by whoever reads it. There is no clear rule what namespace such pids should be relative to, although you could argue that using the host pid namespace would make more sense. It may be possible to create a portal request to get your pid in the host namespace (although it won't be trivial for technical reasons) which could be used for this, but every client would have to be updated to use it.

For bubblewrap though, --unshare-pid is just toggling a flag in a system call, we can't make any changes in how the kernel works to bend to our wishes. It either is enabled or it is not.

**Comment by damianatorrpm** [comment]
@alexlarsson so where would you propose a fix should be done?
I suppose you want to say in the xserver the way it queries the PID and make an exception for bubblewrap, to use SO_PEERCRED instead of _NET_WM_PID in the case of bubblewrap.

Is it safe to assume that it will always be either PID 0 or 2 so that a potential X patch,
detects container PID when PID is 0 or 2?

**Comment by alexlarsson** [comment]
The X server itself never reads _NET_WM_PID, its just a third party standard that people declared people should set, and some other things read it. The xserver doesn't care about the pid of the client (although it can use SO_PEERCRED for authentication via uid). 

So, the issue is rather in the apps that *read* _NET_WM_PID. Unfortunately these don't have a direct socket to the client, so they cannot use SO_PEERCRED, only the xserver can. Nor are they necessarily in the same pid namespace as the host (although often they are, in the case of the compositor). The ideal way would be to add a _NET_WM_PID_NS field too so readers can translate to whichever namepsace they are in, but according to https://blogs.oracle.com/linux/translating-process-id-between-namespaces there are currently no great way to do such translations. Maybe the xserver could magically do the transformation when you write _NET_WM_PID?

The next best solution would be to add a portal call to get your own pid in the host namespace and then change clients to use that as the value they set for _NET_WM_PID. Hopefully this is mostly set by a few toolkits, so its not as much work as you expect.

I don't know how you *ever* got a pid of 0, that should not happen (getpid() never returns 0). However, pid 2 is the first "app" process in a sandbox (pid 1 is an init-style babysitter process), so it will be a common value you see. Its not the only possible one though, if you fork of child processes in the sandbox they will get pid 3, 4, 5... 

In the overall scheme of things though, how important is _NET_WM_PID? What apps read it currently? Could they use some other API instead?

**Comment by ofourdan** [comment]
I cannot say I am thrilled with adding support for EWMH props in Xwayland, but as noted, this cannot be fixed from the clients or toolkits considering they just cannot tell their actual PID in the global PID namespace, so I posted that MR: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/440

We'll see how that goes.
