### ISSUE TITLE
[Feature] Option to let wrapped processes know they're in a container

### ISSUE THREAD

**Issue by matthew-cline** [containers/bubblewrap#414]
The command [`systemd-detect-virt`](https://www.man7.org/linux/man-pages/man1/systemd-detect-virt.1.html) will try to detect if it's executed in a container, but it can't detect being executed in a bubblewrap container.  `bwrap` could have a command line option that would clue in `systemd-detect-virt` to the fact that it's in a container.  The code used to detect containers is [here](https://github.com/systemd/systemd/blob/main/src/basic/virt.c#L551).

A project/sysadmin using bubblewrap could do this on their own, but a command line option would allow this to be done easily without them having to dig through systemd code.

NOTE: I have no use cases in mind for this proposal, just the notion that any scripts out there using `systemd-detect-virt` probably have a good reason for doing so.

**Comment by smcv** [comment]
> A project/sysadmin using bubblewrap could do this on their own

bubblewrap is mechanism more than policy; it *can* implement various parts of https://systemd.io/CONTAINER_INTERFACE/, but it does not force you to do so. I would recommend that projects/sysadmins using bubblewrap for more than a trivial container should set up the necessary information for systemd-detect-virt ([Flatpak does](https://github.com/flatpak/flatpak/pull/3821), and [so does Steam's pressure-vessel](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/215)), but I don't think it's appropriate for bubblewrap to choose how they should do that.

> a command line option would allow this to be done easily without them having to dig through systemd code

How would you implement this? If you think about it, I think you'll come to the conclusion that it isn't possible in general.

We could set environment variable `container=bubblewrap` on pid 1 of the container, but the container doesn't necessarily have a pid 1 (if you don't use `--unshare-pid` then pid 1 is the host system's init). If bwrap is providing pid 1 for the container (with `--unshare-pid` and not `--as-pid-1`, then there is currently no way to set environment variables in pid 1 (`--setenv container bubblewrap` doesn't currently affect it), and perhaps there should be: *that* would be an achievable feature request. However, that won't *always* tell `systemd-detect-virt` that it's in a container.

We could create `/run/host/container-manager` (and in fact both Flatpak and pressure-vessel do), but that's only possible if the filesystem arguments mean that either `/run/host/container-manager` already exists, or `/run` or `/run/host` is writeable by bubblewrap. If you do something simpler like `bwrap --bind / / --dev /dev --proc /proc`, then `/run/host` will not usually exist and it will not usually be possible for bwrap to create it.

Because bwrap has to be setuid on some systems, adding code to it can be a security risk: we have to be sure that new code cannot be used by an attacker to escalate to root privileges. As a result, it's often safer to put "business logic" in something higher-level that uses bwrap, such as Flatpak.

When using something higher-level than bubblewrap, I think it would also be more appropriate to announce the container type using the name of the higher-level thing (like Flatpak), rather than bubblewrap itself. If you can tell that you're in a bubblewrap container, that's relatively meaningless: bubblewrap is mechanism rather than policy, so there's an unlimited number of things that *might* be true about that environment. If you can tell that you're in a Flatpak container, that's more useful: you can reason about its behaviour, and it has "APIs" like `/.flatpak-info` and `/run/host` to tell you more about what's going on.

**Comment by matthew-cline** [comment]
I see your point.
