### ISSUE TITLE
Incorrect bind-try syntax causes 'Permission denied'

### ISSUE THREAD

**Issue by WilliamDEdwards** [containers/bubblewrap#415]
I made a mistake in a '--bind-try' argument by doing:

`--bind-try /run/mysqld/mysqld.sock`

When trying to invoke `bwrap`, I get 'Permission denied':

```
root@unix:~# su - alentink -s /usr/local/bin/jailshell
bwrap: execvp /home/alentink: Permission denied
```

After correcting the syntax to:

`--bind-try /run/mysqld/mysqld.sock /run/mysqld/mysqld.sock`

... I can log in successfully:

```
root@unix:~# su - alentink -s /usr/local/bin/jailshell
alentink@unix:~$
```

I'm new to Bubblewrap, so maybe this is completely expected. Bubblewrap internals must have some reason to return 'Permission denied'. But the error message is confusing at least :)

**Comment by smcv** [comment]
Because you gave `--bind-try` too few arguments, the interpretation of every subsequent argument was off-by-one, so bwrap interpreted them in a way that ended up being meaningless.

I'm guessing you meant to run something like this:

```
bwrap ... --bind-try /run/mysqld/mysqld.sock /run/mysqld/mysqld.sock --chdir /home/alentink /bin/bash -i
      |<--                                        bwrap options                        -->| |<-- command to run -->|
```

However, you missed out an argument, something like this:

```
bwrap ... --bind-try /run/mysqld/mysqld.sock --chdir /home/alentink /bin/bash -i
```

bwrap has no way to know that you *didn't* mean "try to mount `/run/mysqld/mysqld.sock` on `./--chdir`" - that would be an odd filename to use, but the design philosophy of Unix command-line tools is "you asked for it, you got it" (or alternatively "be careful what you ask for").

Because of that miscounting, the the first non-option argument (not starting with `-` and not an expected argument to a known option starting with `-`) is `/home/alentink`, so bwrap assumes you meant to run that "executable" with arguments `/bin/bash -i`, like this:

```
bwrap ... --bind-try /run/mysqld/mysqld.sock --chdir /home/alentink /bin/bash -i
      |<--           bwrap options              -->| |<-- command to run -->|
```

But `/home/alentink` is not actually an executable regular file, so `execve()` fails with "Permission denied".

bwrap's command-line parsing has to be quite simplistic for security reasons: in some system configurations it needs to be setuid root, so every line of code and every external library that it links is an increase to its attack surface, potentially making it possible for an attacker to use it for privilege escalation.

**Comment by WilliamDEdwards** [comment]
Understood. I assumed the parser contained some more logic, but I understand why that choice has been made.

Closing.
