### ISSUE TITLE
Using bwrap as a shell for logged users.

### ISSUE THREAD

**Issue by bryn1u** [containers/bubblewrap#424]
Hello,

Im using bwrap as a shell based on your example:

root@server.proton.edu.pl:[]:#> cat /etc/passwd | grep edek
edek: x :1004:1006::/home/edek:/usr/bin/dupa
root@server.proton.edu.pl:[]:#> cat /usr/bin/dupa
#!/usr/bin/env bash
set -euo pipefail
(exec bwrap --ro-bind /usr /usr \
      --dir /tmp \
      --dir /var \
      --symlink ../tmp var/tmp \
      --proc /proc \
      --dev /dev \
      --ro-bind /etc/resolv.conf /etc/resolv.conf \
      --symlink usr/lib /lib \
      --symlink usr/lib64 /lib64 \
      --symlink usr/bin /bin \
      --symlink usr/sbin /sbin \
      --bind /home/`id -un` /home/`id -un` \
      --unshare-all \
      --share-net \
      --die-with-parent \
      --dir /run/user/$(id -u) \
      --setenv XDG_RUNTIME_DIR "/run/user/`id -u`" \
      --setenv PS1 "Proton$ " \
      --file 11 /etc/passwd \
      --file 12 /etc/group \
      /bin/bash) \
    11< <(getent passwd $UID 65534) \
    12< <(getent group $(id -g) 65534) \
root@server.proton.edu.pl:[~]:#>
Im wondering if possible is keep alive screen session after logout or any application  ? Because when i logout everything is killed. 

Thank you,

**Comment by brandsimon** [comment]
Have you tried removing the option ` --die-with-parent `?

**Comment by smcv** [comment]
The scripts in `demos` are what the directory name suggests: demonstrations, not a production-ready framework for confining user sessions. The usual way to use bubblewrap is to build a larger application around it (Flatpak is a good example).

If you create a new pid namespace (`--unshare-pid` or `--unshare-all`), then the child process will behave as documented in `pid_namespaces(7)`: when process 1 of the pid namespace exits, everything else in the pid namespace is terminated with `SIGKILL` by the kernel. This is how pid namespaces work in the Linux kernel, and bubblewrap is not able to change this behaviour.

If you want to create a pid namespace that persists, you will probably need some way to manage those pid namespaces - perhaps by running bwrap without `--die-with-parent`, and having something like `screen -dRR` instead of `bash` as its child process? Or perhaps writing some sort of system service that creates and reuses a pid namespace per uid, or a PAM module, and then passing those pid namespaces to bwrap as a `--pidns`?

Doing either of those is outside bwrap's scope, but bwrap is an example of a building block you might find useful in setting up one of those.
