### ISSUE TITLE
Subsequent --bind arguments potentially being ignored when checking if a file exists and creating directories

### ISSUE THREAD

**Issue by K4rakara** [containers/bubblewrap#427]
The following command results in firefox running and storing its files in `~/.opt/mozilla`, but also creates the `~/.mozilla` directory, with no files in it:

```sh
exec bwrap \
  --bind / / \
  --bind $HOME/.opt/mozilla $HOME/.mozilla \
  firefox;
```

This might suggest that the `--bind` argument is ignored.

**Comment by charmander** [comment]
The bind mount needs a mountpoint, which bwrap creates if it doesn’t exist. Since the real `/` is mounted as `/`, `$HOME/.mozilla` is created in the corresponding location. (That is to say: the `--bind` argument isn’t being ignored.)

I don’t know if there’s a simpler workaround to this than an overlay mount.

**Comment by smcv** [comment]
Yes, this is how mounting works. We can't mount anything onto a mount point that doesn't exist, and creating the mount point is not a bug.
