### ISSUE TITLE
Cannot access /proc/<pid>/exe of shared proc filesystem

### ISSUE THREAD

**Issue by agorgl** [containers/bubblewrap#431]
What causes the following behavior?
```
$ bwrap --dev-bind / / bash -c "ls /proc/$$/exe"
ls: cannot access '/proc/396260/exe': Permission denied
```
I have program that checks /proc/$ppid/exe to check if its' parent process is alive, and this fails, similar to the POC above when sandboxed. Why is that?

**Comment by charmander** [comment]
The `$$` in the double-quoted string is expanded by the shell running bwrap. You could use single quotes, for example:

```sh
bwrap --dev-bind / / bash -c 'ls /proc/$$/exe'
```

**Comment by hartwork** [comment]
Interesting!

```console
# bwrap --dev-bind / / bash -c 'ls /proc/$$/exe'  # single quotes
/proc/24421/exe

# bwrap --dev-bind / / bash -c "ls /proc/$$/exe"  # double quotes
ls: cannot access '/proc/9929/exe': Permission denied

# ls -l /proc/$$/exe | sed "s,${USER},user,g"
lrwxrwxrwx 1 user user 0 24. Feb 19:23 /proc/9929/exe -> /bin/bash
```

I believe procfs has some files where it pretends to be a symlink but then it isn't. Maybe something like that is at work here?

**Comment by smcv** [comment]
> What causes ... ?

About 90% of the time when asking this question about bubblewrap, the answer is "because it's the only thing the kernel will allow, for some security-related reason".

> I believe procfs has some files where it pretends to be a symlink but then it isn't

Yes, `/proc/*/exe` is a "magic symlink" with special kernel-level semantics.

In `bash -c 'ls /proc/$$/exe'`, `$$` expands to the process ID of the `bash -c` process, which is inside the bubblewrap container.

In `bash -c "ls /proc/$$/exe"`, the variable expansion is done outside the bubblewrap container before running `bwrap`, so `$$` expands to the process ID of the shell from which you ran `bwrap`. This is outside the bubblewrap container, so it seems reasonable to expect that kernel-level security restrictions might prevent you from accessing that.

I don't know exactly *which* kernel-level security restriction is the relevant one here, but it's unlikely that changes to bubblewrap are going to avoid it. Accessing process parameters in `/proc/<pid>` is often guarded by the same permission checks as `ptrace(2)`, and if programs inside the sandbox were allowed to trace programs outside the sandbox, it wouldn't be a very good sandbox: there would be lots of ways a program inside the sandbox could leak information from outside, or even cause arbitrary code execution outside.

> I have program that checks /proc/$ppid/exe to check if its' parent process is alive

You might find `bwrap --die-with-parent` useful.

**Comment by rusty-snake** [comment]
> 5. …
>    b) Deny access if _neither_ of the following is true:
>    - The caller and the target process are in the same user namespace, and the caller's capabilities are a superset of the target process's permitted capabilities.
>    - The caller has the `CAP_SYS_PTRACE` capability in the target process's user namespace.
