### ISSUE TITLE
Question: support on non-metal EC2 instances?

### ISSUE THREAD

**Issue by ljwagerfield** [containers/bubblewrap#450]
**_This is a question, not a bug or feature request._**

Does bubblewrap fully support being run on non-metal EC2 instances?

My concern with "trying it to find out" is that the security guards might silently fail while the process itself appears to run successfully, giving me the false sense of security it's working when it isn't 😅 . So I thought it would be safer to ask.

I'm aware bubblewrap doesn't use KVM, so won't have the same limitations as other sandboxing tools like Ignite/FirecrackerVM (which require physical hosts / metal EC2 instances), but I'm equally naive on the exact system requirements for bubblewrap, and whether non-metal EC2 instances fully support them.

I'd really appreciate any help, and apologies in advance if GH isn't the right place for these sorts of questions 🙏

**Comment by smcv** [comment]
> Does bubblewrap fully support being run on non-metal EC2 instances?

I don't know what a "non-metal EC2 instance" provides, but bubblewrap is using a new user namespace, similar to for example `podman`. I assume a "non-metal EC2 instance" is using either a virtual machine or a container or both.

If run in a virtual machine with no user-space containers, like `qemu-system-x86_64 -enable-kvm` or Google Cloud virtual machines, it should work fine.

If run inside a "larger" container technology like docker, podman or lxc, then it might work, or not, depending what the "larger" container allows. It's known to be possible to run in Docker with non-default seccomp rules, or with `docker run --privileged`, but not with Docker's default settings.

If run in a chroot, it's [known *not* to work](https://github.com/containers/bubblewrap/issues/135) (solutions welcome, I tried to fix this myself but was unable to find the right combination of mount operations).

> My concern with "trying it to find out" is that the security guards might silently fail while the process itself appears to run successfully, giving me the false sense of security it's working when it isn't

I am not aware of situations where running bubblewrap inside a container would grant more privileges than the same bubblewrap command outside a container: if it can run its child process successfully, then everything is probably working as intended. However, it is provided as-is, with no warranty, and what software you are willing to trust is up to you.

Note that bubblewrap is relatively low-level: it's a tool for making security boundaries, rather than a ready-made security boundary. So if you want to use it to wrap untrusted software, you will need to be careful how you set up its command-line to prevent sandbox escapes.

**Comment by ljwagerfield** [comment]
Thank you @smcv, that's all really useful 😄 

> if you want to use it to wrap untrusted software, you will need to be careful how you set up its command-line to prevent sandbox escapes.

I plan to use `--unshare-all`, no `--share-*` flags, and `--bind` an empty folder, such that the host and process can communicate. Assuming I don't introduce my own vulns in the communication (such as executing files that appear in said folder!), I assume this is enough to prevent sandbox escapes?
