### ISSUE TITLE
Override symlink that already exists in existing mount

### ISSUE THREAD

**Issue by WilliamDEdwards** [containers/bubblewrap#479]
Hi,

I'd like to mount a directory read-only, but override one of the symlinks in that directory.

The first issue, writing to a directory that's read-only, I solved by mounting the directory with `--bind` and then `--remount-ro` after I'm done.

The second issue, overriding a symlink that already exists, I haven't solved yet. As expected, this:

```
--bind /etc/alternatives /etc/alternatives \
--symlink usr/bin/program1.0 /etc/alternatives/program \
--remount-ro /etc/alternatives \
```

... yields:

`bwrap: Can't make symlink at /etc/alternatives/program: File exists`

Does anyone have a creative idea to override a symlink, without having to binding the contents of `/etc/alternatives` -without the symlink- manually?

**Comment by smcv** [comment]
> I'd like to mount a directory read-only, but override one of the symlinks in that directory

I don't think you can, because the `mount(2)` system call follows symlinks and does not have a way to not follow symlinks, so we always have to mount over the target of the symlink and never over the symlink itself. What bubblewrap can do is constrained by what the kernel will let us do.

The only way you might be able to do this is with an overlay filesystem, but as far as I know, unprivileged processes cannot usually mount an overlayfs, even if they create a user namespace like bubblewrap does (Ubuntu kernels have/had a patch to allow this, but that has led to at least one [root privilege escalation vulnerability](https://lwn.net/Articles/671641/)).

**Comment by WilliamDEdwards** [comment]
> > I'd like to mount a directory read-only, but override one of the symlinks in that directory
> 
> I don't think you can, because the `mount(2)` system call follows symlinks and does not have a way to not follow symlinks, so we always have to mount over the target of the symlink and never over the symlink itself. What bubblewrap can do is constrained by what the kernel will let us do.
> 
> The only way you might be able to do this is with an overlay filesystem, but as far as I know, unprivileged processes cannot usually mount an overlayfs, even if they create a user namespace like bubblewrap does (Ubuntu kernels have/had a patch to allow this, but that has led to at least one [root privilege escalation vulnerability](https://lwn.net/Articles/671641/)).

Alright, thanks. I'll just `--ro-bind` everything inside `/etc/alternatives`, except for what I want to symlink, manually.

**Comment by Maryse47** [comment]
@smcv

> The only way you might be able to do this is with an overlay filesystem, but as far as I know, unprivileged processes cannot usually mount an overlayfs, even if they create a user namespace like bubblewrap does (Ubuntu kernels have/had a patch to allow this, but that has led to at least one root privilege escalation vulnerability).

just FYI unprivileged mounts for overlayfs [were merged](https://github.com/torvalds/linux/commit/459c7c565ac36ba09ffbf24231147f408fde4203) some time ago in upstream linux kernel
