### ISSUE TITLE
Use commands in bwrap command

### ISSUE THREAD

**Issue by WilliamDEdwards** [containers/bubblewrap#480]
It's possible to use commands when constructing the bwrap command, e.g.:

`--symlink /usr/bin/program"$(cat ${HOME}/version_number.txt)" /etc/alternatives/program \`

Is this a generally accepted practice?

**Comment by smcv** [comment]
This is more of a question about shell scripting than a question about bubblewrap. Please do whatever you need to do to form a command-line that has the behaviour you are looking for.

It's very common to build up a bubblewrap command-line programmatically, and then run it. Flatpak, libgnome-desktop and pressure-vessel all do this (although from C code rather than a shell script).

Shell script error-handling is generally really painful, so I would usually recommend using a programming language with fewer sharp edges than shell script. If you don't have elaborate requirements, then Python's `subprocess` module might be a good choice. Anything where you can build up an `argv` array and then run it (as an array of arguments, rather than a single string) is potentially suitable.
