### ISSUE TITLE
How to allow deletion of bound file ?

### ISSUE THREAD

**Issue by q3cpma** [containers/bubblewrap#497]
Hello and first of all, a big thank for your project. I'm trying to replace
firejail and all its problems (like not accepting some characters - e.g. &, ! -
in parameter paths) and I find bubblewrap much more elegant and simple, even if
a bit lacking in online mindshare and thus examples.

My first conversion target being mupdf-gl, I managed to craft a near optimal
script, but I don't know how to allow the deletion of bound files (mupdf calls
unlink on ~/.mupdf.history).

Here's the current script for information:
```
#!/bin/sh -eu
last=$(eval echo "\${$#}")
exec bwrap \
    --ro-bind /lib /lib \
    --ro-bind /lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/share/libdrm /usr/share/libdrm \
    --ro-bind /sys /sys \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /dev/dri /dev/dri \
    --ro-bind /etc/ld.so.cache /etc/ld.so.cache \
    --ro-bind ~/.Xauthority ~/.Xauthority \
    --bind ~/.mupdf.history ~/.mupdf.history \
    --tmpfs /tmp \
    --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0 \
    --ro-bind "$PWD/$last" "$PWD/$last" \
    --unshare-all \
    mupdf-gl "$@"
```

And here's a simple example to illustrate my problem:
```
cd
touch aaa
bwrap \
	  --ro-bind /bin /bin \
	  --ro-bind /usr/bin /usr/bin \
	  --ro-bind /usr/lib /usr/lib \
	  --ro-bind /lib64 /lib64 \
	  --bind ~/aaa ~/aaa \
	  sh -c 'rm aaa'
```
which gets me `rm: cannot remove 'aaa': Device or resource busy`.

Everything done with bubblewrap-0.6.1 on Gentoo

**Comment by smcv** [comment]
You can't delete a file that is a mount point. This is not a bubblewrap fact, it's a kernel fact, so bubblewrap cannot change it.

If you want to sandbox an app that deletes a file from `$HOME`, probably your only option is to give it a "fake" home directory and let it write to there instead, something like this:

```
mkdir -p ~/.sandboxed-homes/mupdf
bwrap \
... non-$HOME-related things ... \
    --bind ~/.sandboxed-homes/mupdf ~ \
    --ro-bind ~/.Xauthority ~/.Xauthority \
...
```

so that your `.mupdf.history` ends up at `~/.sandboxed-homes/mupdf/.mupdf.history`. But that won't be compatible with your `$PWD/$last` logic, if that's intended to share the parent directory of the file being viewed and the file happens to be in `$HOME`.

If you are able to modify or configure mupdf to use the [freedesktop.org base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and put its history in `~/.local/state/mupdf/mupdf.history` or `~/.cache/mupdf/mupdf.history` or similar, then you would be able to share `~/.cache/mupdf` or `~/.local/state/mupdf` with the container.

(Or consider using a more-joined-up app framework like Flatpak, which doesn't require you to write your own duct tape for every application individually.)

**Comment by q3cpma** [comment]
Thanks for the fast answer

> You can't delete a file that is a mount point. This is not a bubblewrap fact, it's a kernel fact, so bubblewrap cannot change it.

This is indeed what I feared.

> If you want to sandbox an app that deletes a file from $HOME, probably your only option is to give it a "fake" home directory and let it write to there instead, something like this:

Won't work in this special case, as it updates (reads) the file before deleting it.

> If you are able to modify or configure mupdf to use the freedesktop.org base directory specification and put its history in ~/.local/state/mupdf/mupdf.history or ~/.cache/mupdf/mupdf.history or similar, then you would be able to share ~/.cache/mupdf or ~/.local/state/mupdf with the container.

The patch solution is indeed the one I'll choose.

> (Or consider using a more-joined-up app framework like Flatpak)
If the simplicity of bubblewrap is what made me switch, I doubt I'll want contraptions like Flatpak, but thanks for the advice anyway.
