### ISSUE TITLE
Why the function load_file_data return steal_pointer (&data) ?

### ISSUE THREAD

**Issue by ichdream** [containers/bubblewrap#512]
I find the function `load_file_data` in source file `util.c` return `steal_pointer (&data)`, should it be the pointer to the data ?
I could not understand what the `steal_pointer`is used for.
```c
static inline void *
steal_pointer (void *pp)
{
  void **ptr = (void **) pp;
  void *ref;

  ref = *ptr;
  *ptr = NULL;

  return ref;
}

/* type safety */
#define steal_pointer(pp) \
  (0 ? (*(pp)) : (steal_pointer) (pp))
```
Could anyone help to describe it ?
thanks

**Comment by smcv** [comment]
This is an issue tracker, not a forum or a C tutorial.

`steal_pointer()` is basically [GLib's g_steal_pointer](https://docs.gtk.org/glib/func.steal_pointer.html) (see the linked documentation for more information). It transfers ownership of a pointer, preventing the automatic cleanup from `cleanup_free` from being run.

And, yes, the use of `&` is intentional: its parameter is a pointer to the variable whose contents should be stolen.
