### ISSUE TITLE
fchown error case behaves differently inside bwrap

### ISSUE THREAD

**Issue by sfan5** [containers/bubblewrap#521]
bubblewrap 0.6.2, GNU tar 1.34, glibc 2.35

Reproduction steps:
```bash
mkdir /var/tmp/clean
cd /var/tmp/clean
touch example.txt
tar -cf test.tar --owner=root --group=root example.txt

export LANG=C
args=(
	--proc /proc --dev /dev
	--symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/bin /sbin --ro-bind /usr /usr --proc /proc
	--bind "$PWD" "$PWD" --unshare-all --die-with-parent
)
```

#### Expected behaviour

```bash
$ rm -f example.txt
$ strace tar -xf test.tar --same-owner
[...]
openat(AT_FDCWD, "example.txt", O_WRONLY|O_CREAT|O_EXCL|O_NOCTTY|O_NONBLOCK|O_CLOEXEC, 0600) = 4
utimensat(4, NULL, [UTIME_OMIT, {tv_sec=1658523324, tv_nsec=0} /* 2022-07-22T22:55:24+0200 */], 0) = 0
fchown(4, 0, 0)                         = -1 EPERM (Operation not permitted)
write(2, "tar: ", 5tar: )                    = 5
write(2, "example.txt: Cannot change owner"..., 52example.txt: Cannot change ownership to uid 0, gid 0) = 52
write(2, ": Operation not permitted", 25: Operation not permitted) = 25
[...]
```

#### Actual behaviour

```bash
$ rm -f example.txt
$ bwrap "${args[@]}" strace tar -xf test.tar --same-owner
[...]
openat(AT_FDCWD, "example.txt", O_WRONLY|O_CREAT|O_EXCL|O_NOCTTY|O_NONBLOCK|O_CLOEXEC, 0600) = 4
utimensat(4, NULL, [UTIME_OMIT, {tv_sec=1658523324, tv_nsec=0} /* 2022-07-22T20:55:24+0000 */], 0) = 0
fchown(4, 0, 0)                         = -1 EINVAL (Invalid argument)
write(2, "tar: ", 5tar: )                    = 5
write(2, "example.txt: Cannot change owner"..., 52example.txt: Cannot change ownership to uid 0, gid 0) = 52
write(2, ": Invalid argument", 18: Invalid argument)      = 18
[...]
```

#### Why does this matter

If you use tar with fakeroot it will silently filter EPERM but not EINVAL. tar is sometimes used by Arch package build scripts, which I am running under bubblewrap.
This peculiarity causes them to fail.

**Comment by smcv** [comment]
This is working as designed, unfortunately. With bubblewrap, you're in a user namespace where uid 0 literally doesn't exist: the only uid is your own, and everything else is mapped to the overflow uid (usually 65534), so it is correct that 0 is an invalid argument for `fchown()`. This is the only thing the kernel will let us do without having root privileges on the real system.

If you need more uids in your user namespace, as fakeroot does, then a separate setuid-root tool like uidmap will be necessary. The recommended setup for bubblewrap is completely unprivileged and therefore has no access to extra uids from /etc/subuid.

I'd suggest using Podman or Toolbx for package builds in preference to bubblewrap.

The other way to do package builds without fakeroot or real root is to do the entire build and `make install DESTDIR=...` as your normal uid, then build the tar/cpio/etc. archive with `tar --owner=0 --group=0` or similar. Debian used fakeroot for all package builds in the past, but we have moved away from fakeroot and towards `tar --owner=0 --group=0` in recent years, because fakeroot goes wrong some of the time (particularly if you run build-time tests).

Obviously this only works for packages where there are no files with unusual ownership, or for packages where ownership and permissions can be fixed up in a post-install script rather than being part of the package's tar/cpio archive - but that turns out to cover most of the packages in Debian, and probably most of Arch too.

**Comment by sfan5** [comment]
I feared that this was working as designed, thank you for the detailed explanation.

> I'd suggest using Podman or Toolbx for package builds in preference to bubblewrap: that will usually give you access to a full 65536-uid range.

I have considered containers but it's a bit heavy to essentially duplicate all installed packages when I really just want to run a build without having it accidentally or intentionally mess around with my /home.

**Comment by sfan5** [comment]
I came up with a terrible hack that makes this "work" using seccomp.

<details>
<summary>C code</summary>
<pre lang="c">
#include &lt;stdio.h&gt;
#include &lt;stddef.h&gt;
#include &lt;errno.h&gt;
#include &lt;sys/stat.h&gt;
#include &lt;sys/types.h&gt;
#include &lt;seccomp.h&gt;
<br>
/*
&#9;Use with:
&#9;cc test.c -o test -O -Wall $(pkg-config --libs libseccomp)
&#9;exec {bpf}&lt; &lt;(./test)
&#9;bwrap --seccomp $bpf [...]
&#9;exec {bpf}&lt;&-
*/
<br>
int main(int argc, char **argv)
{
&#9;int rc = -1;
<br>
&#9;scmp_filter_ctx ctx = seccomp_init(SCMP_ACT_ALLOW);
&#9;if (!ctx)
&#9;&#9; goto out;
<br>
&#9;const uint32_t act = SCMP_ACT_ERRNO(EPERM);
<br>
&#9;rc = seccomp_rule_add(ctx, act, SCMP_SYS(chown), 1, SCMP_A1(SCMP_CMP_EQ, 0));
&#9;if (rc &lt; 0)
&#9;&#9; goto out;
&#9;rc = seccomp_rule_add(ctx, act, SCMP_SYS(fchown), 1, SCMP_A1(SCMP_CMP_EQ, 0));
&#9;if (rc &lt; 0)
&#9;&#9; goto out;
&#9;rc = seccomp_rule_add(ctx, act, SCMP_SYS(lchown), 1, SCMP_A1(SCMP_CMP_EQ, 0));
&#9;if (rc &lt; 0)
&#9;&#9; goto out;
&#9;rc = seccomp_rule_add(ctx, act, SCMP_SYS(fchownat), 1, SCMP_A2(SCMP_CMP_EQ, 0));
&#9;if (rc &lt; 0)
&#9;&#9; goto out;
<br>
&#9;rc = seccomp_export_bpf(ctx, 1);
<br>
out:
&#9;seccomp_release(ctx);
&#9;if (rc != 0)
&#9;&#9;printf("errno %d\n", rc);
&#9;return (rc == 0) ? 0 : 1;
}
</pre>
</details>

But actually after reading user_namespaces(7) I'm wondering whether bubblewrap couldn't just write a second entry to `uid_map` to map uid 0 inside its namespace too. This isn't privileged, is it?
Would this break anything else?

**Comment by rusty-snake** [comment]
It is privileged because mapping more that the current euid requires `CAP_SETFCAP` in the parent user-namespaces.

What you can do is playing with `--userns`,`--usern2` or `--userns-block-fd`. Or use other tools than bwrap.

**Comment by rusty-snake** [comment]
```
unshare --map-users=auto --map-user=0 --map-groups=auto --map-group=0 bwrap [bwrap argument that do not cause bwrap to unshare a user namespace] [setpriv --reuid --regid] [program and arguments]
```
