### ISSUE TITLE
ptrace from bwrap fails when attaching to pid's that are outside of bwrap process

### ISSUE THREAD

**Issue by haampie** [containers/bubblewrap#526]
I'm not using `bwrap` as a sandbox, but rather just to bind mount some paths.

In that context I was hoping I could run `strace -p [pid of a process that is not a subprocess of bwrap]`.

But trying to run strace on the parent process of bwrap itself fails:

```
$ bwrap --dev-bind / / strace -p $$
strace: attach: ptrace(PTRACE_SEIZE, 128146): Operation not permitted
```

whereas this works:

```
$ strace -p $$
strace: Process 128146 attached
wait4(-1,
```

Nothing changes with `--cap-add ALL`

Is there a way to get this to work?

**Comment by smcv** [comment]
If the kernel won't allow something, then bwrap is not in a position to force it.

In the [documentation of ptrace access mode checking](https://manpages.debian.org/bullseye/manpages-dev/ptrace.2.en.html#Ptrace_access_mode_checking), it looks like you are failing check 5b:

> 5.b) Deny access if neither of the following is true:
> * The caller and the target process are in the same user namespace, and the caller's capabilities are a superset of the target process's permitted capabilities.
> * The caller has the CAP_SYS_PTRACE capability in the target process's user namespace.

The first bullet point fails because the caller (strace) and the target process (pid 128146) are in different user namespaces. Putting the caller in a separate user namespace is fundamental to how bwrap works: without that, it would not be able to do its job.

The second bullet point fails because process 128146 is running in the "init namespace" (the global user namespace that contains all your normal processes), and only root-privileged processes can get access to `CAP_SYS_PTRACE` in that namespace.

`--cap-add ALL` means the strace process gets `CAP_SYS_PTRACE` in the new user namespace created by bwrap, but that doesn't affect its credentials in the init namespace.

References: `ptrace(2)`, `user_namespaces(7)`, `credentials(7)`.
