### ISSUE TITLE
Support `--assert-userns-disabled` with `--unshare-user-try`

### ISSUE THREAD

**Issue by cgzones** [containers/bubblewrap#563]
Currently `--assert-userns-disabled` requires `--unshare-user` and thus does not work with `--unshare-user-try`/`--unshare-all`.
Since the difference between `--unshare-user` and `--unshare-user-try` is the later permits user namespaces to not be available, which should please `--assert-userns-disabled`, I don't see a reason for the combination to not work.

**Comment by smcv** [comment]
`--assert-userns-disabled` means "I claim that I have already (somehow) prevented new user namespaces, but please check". If you haven't done anything special to prevent entering a new user namespace, then that check will fail: that's expected behaviour.

Its purpose is to be able to enter a pre-existing user namespace with `--userns-fd` or `--userns2-fd`, and verify that the pre-existing user namespace already prevented creation of user namespaces.

Or, if I'm misunderstanding: what scenario are you expecting to work, but it doesn't?

**Comment by cgzones** [comment]
I thought about compatibility with `/proc/sys/kernel/unprivileged_userns_clone` set to `0`, but that already breaks non-setuid setups.
