### ISSUE TITLE
Microphone access (google-chrome, Ubuntu 22)

### ISSUE THREAD

**Issue by wonbug** [containers/bubblewrap#582]
I am using bubblewrap to limit google-chrome's access to the file system (command below). Everything works as expected, except Chrome is not able to access my system microphone for Zoom/Hangouts calls. Is there a permission to add or exclude from the options below to enable microphone access in Chrome? I can confirm it works in Chrome when launched without bwrap. Thanks for your hard work - and apologies in advance if Issues is not the right place to ask for such help.

```
alias chrome="""
setpriv  --inh-caps -all --ambient-caps -all bwrap \
--ro-bind /etc  /etc  \
--ro-bind /lib  /lib  \
--ro-bind /lib64  /lib64  \
--ro-bind /opt/google/chrome/  /opt/google/chrome \
--ro-bind /usr/share/locale  /usr/share/locale  \
--ro-bind /usr/share/zoneinfo  /usr/share/zoneinfo  \
--ro-bind /usr/share/fontconfig  /usr/share/fontconfig  \
--ro-bind /usr/share/fonts /usr/share/fonts  \
--ro-bind /usr/share/icons  /usr/share/icons  \
--ro-bind /usr/share/locale-langpack  /usr/share/locale-langpack \
--ro-bind /usr/share/pixmaps  /usr/share/pixmaps  \
--ro-bind /usr/share/ubuntu  /usr/share/ubuntu  \
--ro-bind /usr/share/themes  /usr/share/themes  \
--ro-bind /usr/share/X11  /usr/share/X11  \
--ro-bind /usr/share/glib-2.0  /usr/share/glib-2.0  \
--ro-bind /usr/share/dconf  /usr/share/dconf  \
--ro-bind /usr/share/mime  /usr/share/mime  \
--ro-bind /usr/local/share  /usr/local/share  \
--ro-bind /usr/lib/x86_64-linux-gnu  /usr/lib/x86_64-linux-gnu  \
--ro-bind /usr/lib/locale  /usr/lib/locale  \
--ro-bind /sys  /sys  \
--tmpfs /tmp \
--dev-bind /dev /dev \
--proc /proc \
--bind $HOME/Downloads $HOME/Downloads \
--bind $HOME/.config/google-chrome $HOME/.config/google-chrome \
--unshare-pid \
--unshare-ipc \
--unshare-uts \
--unshare-cgroup \
--new-session \
--hostname RESTRICTED \
--die-with-parent \
/opt/google/chrome/chrome"""
```

**Comment by smcv** [comment]
I don't know how Google Chrome wants to access your microphone, and it is not a bubblewrap maintainer responsibility to know the details of specific programs. bubblewrap is a toolkit for making a container/sandbox, not a ready-made container/sandbox for any specific application.

If it's using PulseAudio, take a look at the bubblewrap options that Flatpak uses in https://github.com/flatpak/flatpak/blob/main/common/flatpak-run-pulseaudio.c. In general it's not a simple thing to set this up, because PulseAudio server discovery has grown quite a lot of complexity over time, but if you know which code paths are relevant to your specific system then you can discard a lot of the complexity.

Similarly, if it's using Pipewire, https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/pressure-vessel/wrap-pipewire.c might be helpful.

If you just want it to work, I would recommend using a higher-level framework like Flatpak. There are Flatpak apps available for the proprietary Google Chrome, the open-source Chromium, and "ungoogled Chromium" which removes various features that rely on contacting Google web services.

**Comment by rusty-snake** [comment]
In both cases you need to allow the socket which usually resides somewhere under $XDG_RUNTIM_DIR.

**Comment by wonbug** [comment]
Thank you both, @rusty-snake that was indeed the needed directory to allow.
