### ISSUE TITLE
Bug: saved ID is not preserved, UID is changed before binding

### ISSUE THREAD

**Issue by anedroid** [containers/bubblewrap#583]
I don't know if this a bug or a feature, but this thing takes a lot of flexibility out of bubblewrap. It uses setuid syscall to set EUID and SUID to RUID on child, which prevents running child as root when bwrap binary have SUID bit enabled unless explicitly invoked with sudo. However setuid() also sets SUID (saved UID), which prevents the user from running bwrap as unprivileged user and the child as another unprivileged user. Why this would be useful? Consider the following Python script:

```python
import os, sys

SECRET = '/home/user-secrets/containers/mozilla'
MOUNTPOINT = '/home/user/.mozilla'
CONFIG_FILE = '/home/user-secrets/containers/mozilla.cfg'

uid = os.getuid()
# DEBUG
if os.access(SECRET, os.R_OK, effective_ids=True):
    print(f"{uid} can read {SECRET}")
else:
    print(f"{uid} cannot read {SECRET}")
# END DEBUG

if uid == 1000: # user
    os.execvp('sudo', ('sudo', '--', os.path.abspath(__file__), *sys.argv[1:])) # run self as root
elif uid == 0: # root
    os.setgroups([])
    os.setgid(1000)
    os.setresuid(1000, 1001, 1001)
    # run self in bwrap and bind secret storage
    os.execvp('bwrap', ('bwrap', '--dev-bind', '/', '/', '--bind', SECRET, MOUNTPOINT, '--', os.path.abspath(__file__), *sys.argv[1:]))
elif uid == 1001: # user-secrets
    os.seteuid(1001)
    with open(CONFIG_FILE) as fd: config = fd.read()
    ... # load some configs, do something
    os.setuid(1000) # drop user-secrets privileges
    os.execvp('firefox', ('firefox', *sys.argv[1:])) # run Firefox as user with access to secret storage
```

This script launches Firefox and makes its data inaccessible for other programs runned as the same user, because `.mozilla` contains sensitive data. Because if some malicious program copies that folder to another machine, one may get access to user online accounts without knowing credentials and bypassing 2FA. In fact, this script is a simplified version of what my project does: it allows everybody use bwrap and their "shadow user" (like `user-secrets`) to create lightweight containers with secret storage.

Without preserving saved UID bwrap would have to be run as root, which increases attack surface, especially taking into account that in my project users can pass any arguments to bwrap in a config file owned by a shadow user. Bwrap should be able to access only files which `user-secrets` can access (and `user`, because they belong to the same group). So my approach is to keep saved ID unchanged and use setresuid syscall, which sets RUID, EUID and SUID explicitly. For example (in Python as I don't know C):

```python
credentials = os.getuid()
... # unshare & bind & etc.
try:
    os.setresuid(credentials[1], credentials[1], credentials[2])
except PermissionError:
    ... # display some error message
else:
    os.execvpe(command, (command, *argv), env)
```

**Comment by rusty-snake** [comment]
Note, the saved-UID will be set to the real/effective-UID during `execve` in the most case (SUID-binaries are special).

The fact that you can not `setuid(1001)` inside of (unprivileged) bwrap comes from the user-namespace which can only a mapping for `1000`.

**Comment by anedroid** [comment]
I didn't know about `execve` modifying UID attributes. You are correct, SUID is being changed into EUID and if it's a setuid-binary, EUID is first set to the owner of the file. In both cases, SUID gets overwritten by EUID value.

I am aware that without root privileges, a new user namespace must be created first. Bwrap does this automatically, I can check that with `ls -l /` – the ownership of other user's files is hidden and replaced with `nobody:nogroup`. If bwrap have setuid bit enabled, it does not create new user namespace by default, because it doesn't have to. Only setuid is disabled inside the container, i.e. child processes cannot use sudo. I can only drop privileges.

At the end, it's enough if the child process's UIDs are equal to (1000, 1000, 1000) (from caller's RUID). I analysed the possible solutions and here are results:

## 1. setresuid(1000, 1001, 1001)

Bwrap runs with effective UID 997, access `user-secrets`'s storage and run child as `user`. Because EUID wasn't 0, a new user namespace must be created at the cost of some flexibility. In contrast to other container tools, the one I develop doesn't aim to isolate the container from the host, rather to give it a little bit more privileges, but to avoid running it as root. The advantage on the other side is more security. Maybe I could manage that.

## 2. setresuid(1000, 1001, 1001) & setuid bwrap

Bwrap runs with effective UID 0, saved UID gets lost. A new pure mount namespace is being created, then to avoid privilege escalation, bwrap drops privileges and become UID 1000. Unfortunately now it cannot access secret storage, which defeats the purpose of my project entirely.

## 3. sudo bwrap

Bwrap runs with UID 0 (real 0, effective 0, saved 0). Now it's able to access files of all shadow users. Hopefully even if someone will bind someone else directory, nothing wrong should happen as long as they run as themselves. But what about other arguments? I doubt allowing anybody run bwrap as root with whatever arguments except the child process always drops privileges would be safe. I would need to filter them and perform a lot of security checks, but it's easy to miss something. Complexity is an enemy of good security.

## Conclusion

Option 2. would be perfect, but it doesn't work and now I see there's nothing bubblewrap cannot do, because it's Linux changing saved UID. I think the easiest would be option 1. – user namespace. But only a theory. In practice there's still a bug.

```python
import os, sys

uid = os.getuid()

if uid == 1000:
    os.execvp('sudo', ('sudo', '--', os.path.abspath(__file__), *sys.argv[1:]))
else:
    os.setresuid(1000, 1001, 1001)
    os.execvp('bwrap', ('bwrap', '--unshare-user', '--bind', '/', '/', '--', 'firefox', *sys.argv[1:]))
```

Throws an error:

```
bwrap: Unexpected setuid user 1001, should be 0
```

Really?

**Comment by smcv** [comment]
> This script launches Firefox and makes its data inaccessible for other programs runned as the same user

Raising privilege like this might be a valid thing to do (although I would personally be very cautious about it), but it is not bubblewrap's security model. bubblewrap is intended to give the sandboxed programs a level of access/privilege that is less than or equal to the level of access/privilege of the caller, whereas you are using it (as part of a larger system involving sudo and your Python script) as a way to get a level of access/privilege that is (effectively) strictly greater than the caller's.

More generally, this is going to be a difficult security model to get right, because it is a relatively central assumption of Unix desktop environments that the desktop session is at least as high-privilege as any of the programs that run in it. Some examples of scenarios to consider:

* a process outside the bubblewrap sandbox uses ptrace() (the same mechanism that gdb uses) to remote-control Firefox
* a process outside the bubblewrap sandbox writes to a file in ~/.config, Firefox reads that file, and Firefox executes arbitrary code as a result of it
* a process outside the bubblewrap sandbox provides the X11 or Wayland display, Firefox trusts messages from that display server, but the user outside the sandbox has total control over the X11 or Wayland display and can use it to trick Firefox into executing arbitrary code
* a process outside the bubblewrap sandbox provides a D-Bus session service, Firefox trusts messages from that service, but the user outside the sandbox has total control over the dbus-daemon and the session service, and can use them to trick Firefox into executing arbitrary code
* Firefox invokes an arbitrary program as a MIME-type handler (for example file-roller or another archive manager to open a downloaded zip file), and the arbitrary program executes arbitrary attacker-controlled code as a result of a scenario similar to one of the above

I'm sure you can construct a system that avoids those attacks with enough thought and enough countermeasures (good luck!), but it is not something that I would want to be responsible for myself. Systems like Flatpak and Snap tend to work the other way round: having the desktop session as the highest-privilege component for each user, and having the user's less-trusted programs run in a sandbox that is "less powerful" than the desktop session as a whole.

As I'm sure you have observed from the number of issues open, bubblewrap is competing for its maintainers' limited time with numerous other projects, so I'm sorry but we don't have the resources to add (or necessarily even evaluate) tricky features, especially if they would undermine its current use-cases: if we don't focus on what bubblewrap is already used for, then we are unlikely to have enough time/resources to keep it working well for that limited scope.

Nothing that bubblewrap does is magic, and all of it is something that could equally well be implemented outside bubblewrap - so if you want to have your own, different security model, I would recommend implementing that security model programmatically.

Making use of `/etc/subuid`/`/etc/subgid`, like Podman does, might be an alternative way to get user namespaces that meet your requirements.

> The fact that you can not setuid(1000) inside of (unprivileged) bwrap comes from the user-namespace which can only a mapping for 1001

bubblewrap certainly cannot do anything about kernel limitations: if the kernel will not allow us to do a particular thing, then we cannot do it, however much we might want to. This project has a strict policy of not doing impossible things :-)

> bwrap: Unexpected setuid user 1001, should be 0

Because bwrap is sometimes setuid root, it needs to be written in a defensive way that is paranoid about being invoked by someone who might be tricking it into misusing its privileges. Sometimes this has some collateral damage, because limiting its use-cases is better than having a CVE for a root security flaw.

If you were to write your own user-namespace-manipulation code (possibly based on bubblewrap), then it would not have bubblewrap's setuid legacy, and you could give it whatever security model you want it to have, without being limited by what bubblewrap's maintainers are able to support.
