### ISSUE TITLE
bwrap with --unshare-pid runs twice and leaves a zombie process when ran inside a docker container

### ISSUE THREAD

**Issue by laheau** [containers/bubblewrap#587]
I need to run arbitrary code for my project and my code runs inside a docker container. It is a privileged container since otherwise bwrap does not work. When using the flag `--unshare-pid`, I noticed that it runs two `bwrap` process and the second one stays as a zombie process on exit.
```
root@86134f372bf2:/usr/src/gameplay# ps afjx
 PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
    0    12    12    12 pts/0       24 Ss       0   0:00 bash
   12    19    19    12 pts/0       24 S        0   0:00  \_ bwrap --bind / / --unshare-pid bash
   19    20    19    12 pts/0       24 S        0   0:00      \_ bwrap --bind / / --unshare-pid bash
   20    21    21    12 pts/0       24 S        0   0:00          \_ bash
   21    24    24    12 pts/0       24 R+       0   0:00              \_ ps afjx
    0     1     1     1 ?           -1 Ssl      0   0:00 gameplay
``` 
  
and when exit the shell i get 
```
root@86134f372bf2:/usr/src/gameplay# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1 360972 15608 ?        Ssl  03:30   0:00 gameplay
root        12  0.0  0.0   3952  3124 pts/0    Ss   03:30   0:00 bash
root        20  0.0  0.0      0     0 pts/0    Z    03:30   0:00 [bwrap] <defunct>
root        25  0.0  0.0   6440  2428 pts/0    R+   03:31   0:00 ps aux
```
I am wondering if I did something wrong, if it's intentional, or is it a bug. Any suggestions for sandboxing from the docker container would also be appreciated. I taught about running the unsafe code inside another docker container but I am not sure what is more safe. Virtualization would be possible but it would compromise performance. Thank you for the help.

**Comment by smcv** [comment]
What exact command-line did you use for this; or if you can reproduce the problem with a simpler command-line, what simpler command-line?

**Comment by smcv** [comment]
> I noticed that it runs two bwrap process

That might be intentional/necessary: some bubblewrap features need it to fork and run two parallel processes.

> [bwrap] <defunct>

That's probably a bug.

**Comment by laheau** [comment]
In a folder I have two file:
`Dockerfile`
```
FROM --platform=$BUILDARCH arm64v8/debian:bullseye
RUN apt-get update && apt-get install -y bubblewrap

ENTRYPOINT ["bash", "-c", "sleep 10000"]
``` 
and
`docker-compose.yml`
```
version: "3.9"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always
```

To recreate the zombie process do

```
docker compose up --build
```
In another shell:

```
docker exec -it debug-builder-1 bash
bwrap --bind / / --unshare-pid bash
exit
ps aux
```
and ps aux shows 
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   1956   476 ?        Ss   18:01   0:00 sleep 10000
root         7  0.1  0.0   3820  3028 pts/0    Ss   18:01   0:00 bash
root        14  0.0  0.0      0     0 pts/0    Z    18:01   0:00 [bwrap] <defunct>
root        17  0.0  0.0   6440  2492 pts/0    R+   18:01   0:00 ps aux
```
You can find the files in [this repo](https://github.com/laheau/debug-bwrap).

**Comment by smcv** [comment]
> ENTRYPOINT ["bash", "-c", "sleep 10000"]

bash appears to have optimized this down to `exec sleep 10000` so pid 1 in your container is `sleep`, which is not prepared to have child processes, and therefore doesn't reap them, making it unsuitable to be pid 1 in a container or pid namespace (this has been written about in innumerable places in the context of Docker, [for example](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/)).

When the main process of `bwrap` exited, `bwrap`'s forked subprocess (which in fact is pid 1 for bwrap's pid namespace, and exists exactly so that it can reap child processes) was reparented to pid 1 in the Docker container's namespace. But `sleep` has no idea that it could or should be reaping child processes, because it didn't expect to have any child processes.

Solution: use `docker --init`, or some other mechanism to make process 1 in the container be `tini` or some other trivial init/reaper process (for example you could have tini as the `ENTRYPOINT`); this will leave all other code run in the container (including `sleep` and your shell, if present), to be process 2 and up.

> Any suggestions for sandboxing from the docker container would also be appreciated

Sorry, I do not have enough time available for bwrap to be able to spend it on giving bwrap users detailed advice on how to use it. The main thing to remember is that bwrap provides you with  tools, but it's up to you to use them in a way that is consistent with your security model.

> I need to run arbitrary code

If your arbitrary code can be attacker-supplied and actively hostile, then you are in the most difficult possible situation for secure sandboxing. It might be useful to look at how Flatpak drives bubblewrap, and how other sandboxing frameworks like sandstorm.io apply their sandboxing (which is not bubblewrap, but makes use of many of the same kernel mechanisms that bubblewrap does). Good luck!
