### ISSUE TITLE
[Simple question] Is Bwrap the simplest tool which can be used as file system isolation?

### ISSUE THREAD

**Issue by av930** [containers/bubblewrap#643]
I'm searching for a tool that only supports "file system isolation" on Linux. I build the source multiple times every day to develop my project. Most of the source code for all builds is the same except for a few commits. 
In this situation, I want the root directory of all builds to have the same path. To do that, currently I'm using docker but it's a bit complicated for every developers to handle it, so I'm looking for the simplest tools.

Could bwrap be the best choice for me? or any other tools?

**Comment by rusty-snake** [comment]
Sounds like something you better ask on reddit (or others). What the simplest tool is, is opinion-dependent and the bwrap developers do not necessarily know  all other tools.

> Is Bwrap the simplest tool which can be used as file system isolation?

Simple is the sweet spot on a scale that gets more complicated at both ends. It needs sufficient abstraction to not bother you with implementation details all the time while avoiding an abstraction-study.

> To do that, currently I'm using docker but it's a bit complicated for every developers to handle it, so I'm looking for the simplest tools.

Getting started with docker is faster/easier than with bubblewrap.

> [Simple question]

[Complicate Answer]

**Comment by av930** [comment]
Sorry, I added question on Reddit. https://www.reddit.com/r/linuxquestions/comments/1e66mr0/is_linux_bwrap_proper_to_make_multiple_same/

**Comment by smcv** [comment]
Your question might be simple, but the answer is not. You haven't said what your requirements are or what your security model is (who the attacker is and what capabilities they are assumed to have), so we don't know whether bubblewrap meets your requirements. We also don't know whether it has additional functionality that is not part of your requirements (which would imply that it isn't "the simplest").

bubblewrap is a tool for making sandboxes, but is not a complete, ready-made sandbox with a specific security policy. If a particular bubblewrap invocation happens to meet your requirements, you're welcome to use it, but ensuring that the way you use it fits your security requirements is up to you.

Most of bubblewrap's arguments map 1:1 to specific syscalls and kernel mechanisms, so in that sense it's "simple": it's "closer to the metal" than something like Docker or Podman. Conversely, because many of bubblewrap's arguments map 1:1 to specific syscalls and kernel mechanisms, it's up to you to use them in a way that matches your security policy and there is no convenience layer that will help you to avoid mistakes or design flaws (so in that sense, it isn't simple to use).

I don't think there is any honest response to this question that would make you happy: we are not going to say "yes, bwrap is amazing and you should definitely use it", because that's an over-simplification (and would be likely to create a feeling that we owe you something). We're also unlikely to say "no, bwrap is not for you" without it being obvious that it isn't. So I'm going to close this as not an actionable issue.
