### ISSUE TITLE
Bubblewrapped execve drops privileges

### ISSUE THREAD

**Issue by io12** [containers/bubblewrap#674]
I'm running into a situation where privileges are being dropped when running through bubblewrap, but only after executing another process. Is this a bug? I thought `bwrap --dev-bind / / cmd` was supposed to be close to the same as just `cmd`.

## Example

```sh
$ sudo ./a.py
(1000, 0, 0)
(1000, 0, 0)
$ sudo bwrap --dev-bind / / ./a.py
(1000, 0, 0)
(1000, 1000, 1000)
```

`a.py`:
```python3
#!/usr/bin/env python3

import os

os.setresuid(1000, 0, 0)
print(os.getresuid())
os.execv("./b.py", ["./b.py"])
```

`b.py`:
```python3
#!/usr/bin/env python3

import os

print(os.getresuid())
```

**Comment by smcv** [comment]
bwrap is not really designed to be used with elevated privileges. If you have elevated privileges, you can make the same system calls that bwrap does, more directly, and you don't really need bwrap.

**Comment by smcv** [comment]
> I thought `bwrap --dev-bind / / cmd` was supposed to be close to the same as just `cmd`.

Yes ish, but "close to the same" is not "identical". bwrap makes some changes to the process state that are irreversible and non-optional. One of those changes to the process state is that bwrap always uses prctl `PR_SET_NO_NEW_PRIVS`, which might have an effect on whether elevated privileges are retained.

The various aspects of process state that bwrap manipulates have many subtle interactions, but are also reasonably well documented (for example in `user_namespaces(7)` and `credentials(7)`). In my experience, if there is an interaction that you weren't expecting, the reason is usually either "to prevent a security vulnerability" or "for backward-compatibility".

**Comment by smcv** [comment]
In the usual use-case for `bwrap` (not having elevated privileges), we have to create a new user namespace (otherwise it would not be possible to create a new mount namespace and alter the mount table, which is bwrap's primary purpose). This means that it is likely to be impossible for the real, effective and saved uids to be different: the kernel does not allow unprivileged users to create a user namespace with more than one uid mapped into it.

If you *do* have elevated privileges, then creating a new user namespace is not strictly necessary, but neither is using bwrap. Consider using `unshare(1)`, `newuidmap(1)`, `setpriv(1)` or C code to manipulate process attributes according to your particular requirements, whatever those might be.

**Comment by io12** [comment]
> One of those changes to the process state is that bwrap always uses prctl PR_SET_NO_NEW_PRIVS, which might have an effect on whether elevated privileges are retained.

Thanks so much! That was the issue. Disabling the prctl made the behavior as expected.

**Comment by smcv** [comment]
> Disabling the prctl made the behavior as expected

Using this prctl is security-sensitive, and the maintainers of bubblewrap will not provide security support or fix security vulnerabilities in a version of bubblewrap that has been modified in this way. If you are maintaining a fork of bubblewrap with this change, please do not call it bubblewrap or bwrap.
